[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.10.0" }
wally = { source = "UpliftGames/wally", version = "0.1.1" }
