site_name: Fast Food
site_url: https://lasttalon.github.io/FastFood/
repo_url: https://github.com/LastTalon/FastFood/
edit_uri: ''

theme:
  name: material
  hljs_languages:
    - lua
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Reference:
    - API Reference: api/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
